In [43]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [44]:
df = pd.read_csv('pixar.csv')
df

,film,budget,box_office_us_canada,box_office_other,box_office_worldwide,rotten_tomatoes_score,rotten_tomatoes_counts,metacritic_score,metacritic_counts,cinema_score,imdb_score,imdb_counts
0,Toy Story,30000000.0,223225679,171210907,394436586,100,96,95,26,A,8.3,1089101
1,A Bug's Life,120000000.0,162798565,200460294,363258859,92,91,78,23,A,7.2,319596
2,Toy Story 2,90000000.0,245852179,265506097,511358276,100,172,88,34,A+,7.9,630573
3,"Monsters, Inc.",115000000.0,255873250,272900000,528773250,96,199,79,35,A+,8.1,1000657
4,Finding Nemo,94000000.0,339714978,531300000,871014978,99,270,90,38,A+,8.2,1132877
5,The Incredibles,92000000.0,261441092,370001000,631442092,97,250,90,41,A+,8.0,828986
6,Cars,120000000.0,244082982,217900167,461983149,75,204,73,39,A,7.2,484034
7,Ratatouille,150000000.0,206445654,417280431,623726085,96,253,96,37,A,8.1,851229
8,WALL-E,180000000.0,223808164,297503696,521311860,95,261,95,39,A,8.4,1226415
9,Up,175000000.0,293004164,442094918,735099082,98,297,88,37,A+,8.3,1151249
10,Toy Story 3,200000000.0,415004880,651964823,1066969703,98,313,92,39,A,8.3,908222
11,Cars 2,200000000.0,191452396,368400000,559852396,40,220,57,38,A-,6.2,225724
12,Brave,185000000.0,237283207,301700000,538983207,79,256,69,37,A,7.1,452012
13,Monsters University,200000000.0,268492764,475066843,743559607,80,203,65,41,A,7.2,398903
14,Inside Out,175000000.0,356461711,501149463,857611174,98,387,94,55,A,8.1,834268
15,The Good Dinosaur,175000000.0,123087120,209120551,332207671,75,220,66,37,A,6.7,130324
16,Finding Dory,200000000.0,486295561,542275328,1028570889,94,339,77,48,A,7.2,311793
17,Cars 3,175000000.0,152901115,231029541,383930656,69,234,59,41,A,6.7,128849
18,Coco,175000000.0,210460015,604181157,814641172,97,357,81,48,A+,8.4,618005
19,Incredibles 2,200000000.0,608581744,634223615,1242805359,93,390,80,51,A+,7.5,341353
20,Toy Story 4,200000000.0,434038008,639356585,1073394593,97,459,84,57,A,7.6,288783
21,Onward,175000000.0,61555145,80384897,141940042,88,350,64,56,A-,7.4,174917
22,Soul,150000000.0,946154,120957731,121903885,95,360,83,55,NaN,8.0,392783
23,Luca,NaN,1324302,49788012,51112314,91,303,71,52,NaN,7.4,202404
24,Turning Red,175000000.0,1399001,20414357,21813358,95,289,83,52,NaN,7.0,158649
25,Lightyear,200000000.0,118307188,108118232,226425420,74,319,60,57,A-,6.1,127045
26,Elemental,200000000.0,154426697,342017611,496444308,73,262,58,45,A,7.0,140174
27,Inside Out 2,200000000.0,652980194,1045050771,1698030965,90,313,73,59,A,7.6,168090

In [45]:
df = df.drop_duplicates()
df

,film,budget,box_office_us_canada,box_office_other,box_office_worldwide,rotten_tomatoes_score,rotten_tomatoes_counts,metacritic_score,metacritic_counts,cinema_score,imdb_score,imdb_counts
0,Toy Story,30000000.0,223225679,171210907,394436586,100,96,95,26,A,8.3,1089101
1,A Bug's Life,120000000.0,162798565,200460294,363258859,92,91,78,23,A,7.2,319596
2,Toy Story 2,90000000.0,245852179,265506097,511358276,100,172,88,34,A+,7.9,630573
3,"Monsters, Inc.",115000000.0,255873250,272900000,528773250,96,199,79,35,A+,8.1,1000657
4,Finding Nemo,94000000.0,339714978,531300000,871014978,99,270,90,38,A+,8.2,1132877
5,The Incredibles,92000000.0,261441092,370001000,631442092,97,250,90,41,A+,8.0,828986
6,Cars,120000000.0,244082982,217900167,461983149,75,204,73,39,A,7.2,484034
7,Ratatouille,150000000.0,206445654,417280431,623726085,96,253,96,37,A,8.1,851229
8,WALL-E,180000000.0,223808164,297503696,521311860,95,261,95,39,A,8.4,1226415
9,Up,175000000.0,293004164,442094918,735099082,98,297,88,37,A+,8.3,1151249
10,Toy Story 3,200000000.0,415004880,651964823,1066969703,98,313,92,39,A,8.3,908222
11,Cars 2,200000000.0,191452396,368400000,559852396,40,220,57,38,A-,6.2,225724
12,Brave,185000000.0,237283207,301700000,538983207,79,256,69,37,A,7.1,452012
13,Monsters University,200000000.0,268492764,475066843,743559607,80,203,65,41,A,7.2,398903
14,Inside Out,175000000.0,356461711,501149463,857611174,98,387,94,55,A,8.1,834268
15,The Good Dinosaur,175000000.0,123087120,209120551,332207671,75,220,66,37,A,6.7,130324
16,Finding Dory,200000000.0,486295561,542275328,1028570889,94,339,77,48,A,7.2,311793
17,Cars 3,175000000.0,152901115,231029541,383930656,69,234,59,41,A,6.7,128849
18,Coco,175000000.0,210460015,604181157,814641172,97,357,81,48,A+,8.4,618005
19,Incredibles 2,200000000.0,608581744,634223615,1242805359,93,390,80,51,A+,7.5,341353
20,Toy Story 4,200000000.0,434038008,639356585,1073394593,97,459,84,57,A,7.6,288783
21,Onward,175000000.0,61555145,80384897,141940042,88,350,64,56,A-,7.4,174917
22,Soul,150000000.0,946154,120957731,121903885,95,360,83,55,NaN,8.0,392783
23,Luca,NaN,1324302,49788012,51112314,91,303,71,52,NaN,7.4,202404
24,Turning Red,175000000.0,1399001,20414357,21813358,95,289,83,52,NaN,7.0,158649
25,Lightyear,200000000.0,118307188,108118232,226425420,74,319,60,57,A-,6.1,127045
26,Elemental,200000000.0,154426697,342017611,496444308,73,262,58,45,A,7.0,140174
27,Inside Out 2,200000000.0,652980194,1045050771,1698030965,90,313,73,59,A,7.6,168090

In [46]:
df = df.rename(columns = {'film' : 'Animation', 'budget' : 'Budget',
                'box_office_us_canada' : 'US Box Office', 'box_office_other' : 'World Box Office',
                'box_office_worldwide' : 'Total Box Office', 'rotten_tomatoes_score' : 'Rotten Score',
                'rotten_tomatoes_counts' : 'Rotten Counts', 'metacritic_score' : 'Metacritic Score',
                'metacritic_counts' : 'Metacritic Counts', 'cinema_score' : 'Cinema Score',
                'imdb_score' : 'Imdb Score', 'imdb_counts' : 'Imdb Counts'})
df

,Animation,Budget,US Box Office,World Box Office,Total Box Office,Rotten Score,Rotten Counts,Metacritic Score,Metacritic Counts,Cinema Score,Imdb Score,Imdb Counts
0,Toy Story,30000000.0,223225679,171210907,394436586,100,96,95,26,A,8.3,1089101
1,A Bug's Life,120000000.0,162798565,200460294,363258859,92,91,78,23,A,7.2,319596
2,Toy Story 2,90000000.0,245852179,265506097,511358276,100,172,88,34,A+,7.9,630573
3,"Monsters, Inc.",115000000.0,255873250,272900000,528773250,96,199,79,35,A+,8.1,1000657
4,Finding Nemo,94000000.0,339714978,531300000,871014978,99,270,90,38,A+,8.2,1132877
5,The Incredibles,92000000.0,261441092,370001000,631442092,97,250,90,41,A+,8.0,828986
6,Cars,120000000.0,244082982,217900167,461983149,75,204,73,39,A,7.2,484034
7,Ratatouille,150000000.0,206445654,417280431,623726085,96,253,96,37,A,8.1,851229
8,WALL-E,180000000.0,223808164,297503696,521311860,95,261,95,39,A,8.4,1226415
9,Up,175000000.0,293004164,442094918,735099082,98,297,88,37,A+,8.3,1151249
10,Toy Story 3,200000000.0,415004880,651964823,1066969703,98,313,92,39,A,8.3,908222
11,Cars 2,200000000.0,191452396,368400000,559852396,40,220,57,38,A-,6.2,225724
12,Brave,185000000.0,237283207,301700000,538983207,79,256,69,37,A,7.1,452012
13,Monsters University,200000000.0,268492764,475066843,743559607,80,203,65,41,A,7.2,398903
14,Inside Out,175000000.0,356461711,501149463,857611174,98,387,94,55,A,8.1,834268
15,The Good Dinosaur,175000000.0,123087120,209120551,332207671,75,220,66,37,A,6.7,130324
16,Finding Dory,200000000.0,486295561,542275328,1028570889,94,339,77,48,A,7.2,311793
17,Cars 3,175000000.0,152901115,231029541,383930656,69,234,59,41,A,6.7,128849
18,Coco,175000000.0,210460015,604181157,814641172,97,357,81,48,A+,8.4,618005
19,Incredibles 2,200000000.0,608581744,634223615,1242805359,93,390,80,51,A+,7.5,341353
20,Toy Story 4,200000000.0,434038008,639356585,1073394593,97,459,84,57,A,7.6,288783
21,Onward,175000000.0,61555145,80384897,141940042,88,350,64,56,A-,7.4,174917
22,Soul,150000000.0,946154,120957731,121903885,95,360,83,55,NaN,8.0,392783
23,Luca,NaN,1324302,49788012,51112314,91,303,71,52,NaN,7.4,202404
24,Turning Red,175000000.0,1399001,20414357,21813358,95,289,83,52,NaN,7.0,158649
25,Lightyear,200000000.0,118307188,108118232,226425420,74,319,60,57,A-,6.1,127045
26,Elemental,200000000.0,154426697,342017611,496444308,73,262,58,45,A,7.0,140174
27,Inside Out 2,200000000.0,652980194,1045050771,1698030965,90,313,73,59,A,7.6,168090

In [47]:
df.at[23, 'Budget'] = 165000000
df

,Animation,Budget,US Box Office,World Box Office,Total Box Office,Rotten Score,Rotten Counts,Metacritic Score,Metacritic Counts,Cinema Score,Imdb Score,Imdb Counts
0,Toy Story,30000000.0,223225679,171210907,394436586,100,96,95,26,A,8.3,1089101
1,A Bug's Life,120000000.0,162798565,200460294,363258859,92,91,78,23,A,7.2,319596
2,Toy Story 2,90000000.0,245852179,265506097,511358276,100,172,88,34,A+,7.9,630573
3,"Monsters, Inc.",115000000.0,255873250,272900000,528773250,96,199,79,35,A+,8.1,1000657
4,Finding Nemo,94000000.0,339714978,531300000,871014978,99,270,90,38,A+,8.2,1132877
5,The Incredibles,92000000.0,261441092,370001000,631442092,97,250,90,41,A+,8.0,828986
6,Cars,120000000.0,244082982,217900167,461983149,75,204,73,39,A,7.2,484034
7,Ratatouille,150000000.0,206445654,417280431,623726085,96,253,96,37,A,8.1,851229
8,WALL-E,180000000.0,223808164,297503696,521311860,95,261,95,39,A,8.4,1226415
9,Up,175000000.0,293004164,442094918,735099082,98,297,88,37,A+,8.3,1151249
10,Toy Story 3,200000000.0,415004880,651964823,1066969703,98,313,92,39,A,8.3,908222
11,Cars 2,200000000.0,191452396,368400000,559852396,40,220,57,38,A-,6.2,225724
12,Brave,185000000.0,237283207,301700000,538983207,79,256,69,37,A,7.1,452012
13,Monsters University,200000000.0,268492764,475066843,743559607,80,203,65,41,A,7.2,398903
14,Inside Out,175000000.0,356461711,501149463,857611174,98,387,94,55,A,8.1,834268
15,The Good Dinosaur,175000000.0,123087120,209120551,332207671,75,220,66,37,A,6.7,130324
16,Finding Dory,200000000.0,486295561,542275328,1028570889,94,339,77,48,A,7.2,311793
17,Cars 3,175000000.0,152901115,231029541,383930656,69,234,59,41,A,6.7,128849
18,Coco,175000000.0,210460015,604181157,814641172,97,357,81,48,A+,8.4,618005
19,Incredibles 2,200000000.0,608581744,634223615,1242805359,93,390,80,51,A+,7.5,341353
20,Toy Story 4,200000000.0,434038008,639356585,1073394593,97,459,84,57,A,7.6,288783
21,Onward,175000000.0,61555145,80384897,141940042,88,350,64,56,A-,7.4,174917
22,Soul,150000000.0,946154,120957731,121903885,95,360,83,55,NaN,8.0,392783
23,Luca,165000000.0,1324302,49788012,51112314,91,303,71,52,NaN,7.4,202404
24,Turning Red,175000000.0,1399001,20414357,21813358,95,289,83,52,NaN,7.0,158649
25,Lightyear,200000000.0,118307188,108118232,226425420,74,319,60,57,A-,6.1,127045
26,Elemental,200000000.0,154426697,342017611,496444308,73,262,58,45,A,7.0,140174
27,Inside Out 2,200000000.0,652980194,1045050771,1698030965,90,313,73,59,A,7.6,168090

In [48]:
df.at[(22, 23, 24), 'Cinema Score'] = 'A'
df

,Animation,Budget,US Box Office,World Box Office,Total Box Office,Rotten Score,Rotten Counts,Metacritic Score,Metacritic Counts,Cinema Score,Imdb Score,Imdb Counts
0,Toy Story,30000000.0,223225679,171210907,394436586,100,96,95,26,A,8.3,1089101
1,A Bug's Life,120000000.0,162798565,200460294,363258859,92,91,78,23,A,7.2,319596
2,Toy Story 2,90000000.0,245852179,265506097,511358276,100,172,88,34,A+,7.9,630573
3,"Monsters, Inc.",115000000.0,255873250,272900000,528773250,96,199,79,35,A+,8.1,1000657
4,Finding Nemo,94000000.0,339714978,531300000,871014978,99,270,90,38,A+,8.2,1132877
5,The Incredibles,92000000.0,261441092,370001000,631442092,97,250,90,41,A+,8.0,828986
6,Cars,120000000.0,244082982,217900167,461983149,75,204,73,39,A,7.2,484034
7,Ratatouille,150000000.0,206445654,417280431,623726085,96,253,96,37,A,8.1,851229
8,WALL-E,180000000.0,223808164,297503696,521311860,95,261,95,39,A,8.4,1226415
9,Up,175000000.0,293004164,442094918,735099082,98,297,88,37,A+,8.3,1151249
10,Toy Story 3,200000000.0,415004880,651964823,1066969703,98,313,92,39,A,8.3,908222
11,Cars 2,200000000.0,191452396,368400000,559852396,40,220,57,38,A-,6.2,225724
12,Brave,185000000.0,237283207,301700000,538983207,79,256,69,37,A,7.1,452012
13,Monsters University,200000000.0,268492764,475066843,743559607,80,203,65,41,A,7.2,398903
14,Inside Out,175000000.0,356461711,501149463,857611174,98,387,94,55,A,8.1,834268
15,The Good Dinosaur,175000000.0,123087120,209120551,332207671,75,220,66,37,A,6.7,130324
16,Finding Dory,200000000.0,486295561,542275328,1028570889,94,339,77,48,A,7.2,311793
17,Cars 3,175000000.0,152901115,231029541,383930656,69,234,59,41,A,6.7,128849
18,Coco,175000000.0,210460015,604181157,814641172,97,357,81,48,A+,8.4,618005
19,Incredibles 2,200000000.0,608581744,634223615,1242805359,93,390,80,51,A+,7.5,341353
20,Toy Story 4,200000000.0,434038008,639356585,1073394593,97,459,84,57,A,7.6,288783
21,Onward,175000000.0,61555145,80384897,141940042,88,350,64,56,A-,7.4,174917
22,Soul,150000000.0,946154,120957731,121903885,95,360,83,55,A,8.0,392783
23,Luca,165000000.0,1324302,49788012,51112314,91,303,71,52,A,7.4,202404
24,Turning Red,175000000.0,1399001,20414357,21813358,95,289,83,52,A,7.0,158649
25,Lightyear,200000000.0,118307188,108118232,226425420,74,319,60,57,A-,6.1,127045
26,Elemental,200000000.0,154426697,342017611,496444308,73,262,58,45,A,7.0,140174
27,Inside Out 2,200000000.0,652980194,1045050771,1698030965,90,313,73,59,A,7.6,168090

In [49]:
df['Budget'] = df['Budget'].astype('int')
df.dtypes

Animation             object
Budget                 int64
US Box Office          int64
World Box Office       int64
Total Box Office       int64
Rotten Score           int64
Rotten Counts          int64
Metacritic Score       int64
Metacritic Counts      int64
Cinema Score          object
Imdb Score           float64
Imdb Counts            int64
dtype: object

In [50]:
df

,Animation,Budget,US Box Office,World Box Office,Total Box Office,Rotten Score,Rotten Counts,Metacritic Score,Metacritic Counts,Cinema Score,Imdb Score,Imdb Counts
0,Toy Story,30000000,223225679,171210907,394436586,100,96,95,26,A,8.3,1089101
1,A Bug's Life,120000000,162798565,200460294,363258859,92,91,78,23,A,7.2,319596
2,Toy Story 2,90000000,245852179,265506097,511358276,100,172,88,34,A+,7.9,630573
3,"Monsters, Inc.",115000000,255873250,272900000,528773250,96,199,79,35,A+,8.1,1000657
4,Finding Nemo,94000000,339714978,531300000,871014978,99,270,90,38,A+,8.2,1132877
5,The Incredibles,92000000,261441092,370001000,631442092,97,250,90,41,A+,8.0,828986
6,Cars,120000000,244082982,217900167,461983149,75,204,73,39,A,7.2,484034
7,Ratatouille,150000000,206445654,417280431,623726085,96,253,96,37,A,8.1,851229
8,WALL-E,180000000,223808164,297503696,521311860,95,261,95,39,A,8.4,1226415
9,Up,175000000,293004164,442094918,735099082,98,297,88,37,A+,8.3,1151249
10,Toy Story 3,200000000,415004880,651964823,1066969703,98,313,92,39,A,8.3,908222
11,Cars 2,200000000,191452396,368400000,559852396,40,220,57,38,A-,6.2,225724
12,Brave,185000000,237283207,301700000,538983207,79,256,69,37,A,7.1,452012
13,Monsters University,200000000,268492764,475066843,743559607,80,203,65,41,A,7.2,398903
14,Inside Out,175000000,356461711,501149463,857611174,98,387,94,55,A,8.1,834268
15,The Good Dinosaur,175000000,123087120,209120551,332207671,75,220,66,37,A,6.7,130324
16,Finding Dory,200000000,486295561,542275328,1028570889,94,339,77,48,A,7.2,311793
17,Cars 3,175000000,152901115,231029541,383930656,69,234,59,41,A,6.7,128849
18,Coco,175000000,210460015,604181157,814641172,97,357,81,48,A+,8.4,618005
19,Incredibles 2,200000000,608581744,634223615,1242805359,93,390,80,51,A+,7.5,341353
20,Toy Story 4,200000000,434038008,639356585,1073394593,97,459,84,57,A,7.6,288783
21,Onward,175000000,61555145,80384897,141940042,88,350,64,56,A-,7.4,174917
22,Soul,150000000,946154,120957731,121903885,95,360,83,55,A,8.0,392783
23,Luca,165000000,1324302,49788012,51112314,91,303,71,52,A,7.4,202404
24,Turning Red,175000000,1399001,20414357,21813358,95,289,83,52,A,7.0,158649
25,Lightyear,200000000,118307188,108118232,226425420,74,319,60,57,A-,6.1,127045
26,Elemental,200000000,154426697,342017611,496444308,73,262,58,45,A,7.0,140174
27,Inside Out 2,200000000,652980194,1045050771,1698030965,90,313,73,59,A,7.6,168090

In [51]:
df = df.to_excel('Cleaned Pixar.xlsx', index = False)